language: bash
sudo: required

before_install:
  - docker pull weecology/portal_predictions
  - docker run --name ppred -t -d weecology/portal_predictions /bin/bash
  - docker cp ../portal-forecast-web ppred:/
  - docker exec -i ppred ls portal-forecast-web

script:
  - docker exec -i ppred bash -c "cd portal-forecast-web && Rscript build_website.R"
  - docker cp ppred:/portal-forecast-web/docs/ ./

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  name: Weecology Deploy Bot
  email: weecologydeploy@weecology.org
  keep_history: true
  target_branch: master
  on:
    branch: master