setup_date: '2022-04-05'
setup_R_version:
  platform: x86_64-w64-mingw32
  arch: x86_64
  os: mingw32
  system: x86_64, mingw32
  status: ''
  major: '4'
  minor: '0.5'
  year: '2021'
  month: '03'
  day: '31'
  svn rev: '80133'
  language: R
  version.string: R version 4.0.5 (2021-03-31)
  nickname: Shake and Throw
setup_portalcasting_version: 0.26.0
directory_tree:
  main: '.'
  subs:
  - casts
  - models
  - raw
  - data
  - tmp
downloads_versions: ~

