setup_date: '2022-02-09'
setup_R_version:
  platform: x86_64-pc-linux-gnu
  arch: x86_64
  os: linux-gnu
  system: x86_64, linux-gnu
  status: ''
  major: '4'
  minor: '0.4'
  year: '2021'
  month: '02'
  day: '15'
  svn rev: '80002'
  language: R
  version.string: R version 4.0.4 (2021-02-15)
  nickname: Lost Library Book
setup_portalcasting_version: 0.21.2
directory_tree:
  main: '.'
  subs:
  - casts
  - models
  - raw
  - data
  - tmp
downloads_versions:
- PortalData-3.52.0
- portalPredictions-2022-02-03

