setup:
  date: '2022-11-12'
  R_version:
    platform: x86_64-apple-darwin17.0
    arch: x86_64
    os: darwin17.0
    system: x86_64, darwin17.0
    status: ''
    major: '4'
    minor: '2.0'
    year: '2022'
    month: '04'
    day: '22'
    svn rev: '82229'
    language: R
    version.string: R version 4.2.0 (2022-04-22)
    nickname: Vigorous Calisthenics
  core_package_name: portalcasting
  core_package_version: 0.44.0
tree:
  main: '.'
  subdirectories:
    forecasts: forecasts
    fits: fits
    models: models
    resources: resources
    data: data
raw:
  PortalData_version: 3.140.0
  archive_version: latest
  climate_forecast_version: '2022-11-12'
