# Verifying that the app can be built

on:
  push:
  pull_request:

name: App build

jobs:
  R-CMD-check:
    runs-on: ubuntu-20.04
    env:
      R_DEFAULT_INTERNET_TIMEOUT: 300
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      CRAN_REPO: https://packagemanager.rstudio.com/all/__linux__/focal/latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
