# Verifying that the app can be built

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: App build

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker://weecology/portalcasting:latest
    env:
      R_DEFAULT_INTERNET_TIMEOUT: 300
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v3

      - name: Check
        run: Rscript tests/test_app_build.R
